Your job is to determine the title for the document based on information given in the
document (in the DOCUMENT section).
The title of the document may or may not be explicitly stated in the document.
If the title is not explicitly stated, give a suitable title based on the information provided.
If the title is explicitly stated in the rules, then it should be given in title case.

DOCUMENT:
{document}
